# Generated by Django 4.2.1 on 2023-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('standard', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
